export const PATH_TRANSLATION_MAP = {
  dashboard: 'Dashboard',
  askola: 'Ask Ola',
  file: 'file',
  integrations: 'integrations',
  customer: 'Customers',
  merchandise: 'Merchandise',
  factory: 'Factory',
  invoice: 'Invoice',
  quote: 'Quote',
  purchaseorder: 'Purchase Orders',
  payment: 'Payment',
  settings: 'Settings',
  profile: 'Profile',
  control: 'Tasks',
  mode: 'Payment Mode',
  general_settings: 'Company',
  currency_settings: 'Currency Settings',
  create: 'create',
  edit: 'edit',
  list: 'list',
};

export const ROUTE_CATEGORY_MAP = {
  '': 'Main',
  dashboard: 'Main',
  askola: 'Main',
  file: 'Main',
  integrations: 'Main',
  control: 'Main',
  settings: 'Workspace',
  profile: 'Personal',
  customer: 'Business',
  merchandise: 'Business',
  factory: 'Business',
  quote: 'Finance',
  purchaseorder: 'Finance',
  invoice: 'Finance',
  payment: 'Finance',
};
